---
plugin: aws_ec2
regions:
- us-west-2

# Set individual Variables
compose:
ansible_host: public_ip_address | private_ip_address

# Create groups
keyed_groups:

# add hosts to group for each Name
  - key: tags.Name
    prefix: ""
    separator: ""